### ISSUE TITLE
cannons reset when craft is repiloted

### ISSUE THREAD

**Issue by TylerS1066** [TylerS1066/Movecraft-Cannons#12]
> **Describe the bug**
> When you release/repilot/pilot a craft it resets cannons (but it doesn't if you move! i have movecraft-cannons)
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. setup the cannon
> 2. pilot the craft
> 3. try and use the cannon
> 4. and the cannons reset
> 
> **Expected behavior**
> you need to repay for a cannon and redo everything (not good when your in combat  and like going on your wing for shooting people and you accidently release your craft and stuff)
> 
> **Screenshots**
> 
> 
> **Versions (please complete the following information):**
>  - Movecraft: Alpha 4
>  - Java 16
>  - Minecraft paper 1.16.5
> 
> **Additional context**
> i have towny, movecraft-cannons, movecraft-combat, and cannons
> those should be the important plugins you need to know about
> 
See https://github.com/APDevTeam/Movecraft/issues/443

**Comment by TylerS1066** [comment]
@tskopen can you please give details on which addon versions you are running?

Does this remain a problem without Movecraft-Combat and Movecraft-Towny?

**Comment by tskopen** [comment]
idk if it reamins without movecraft-combat ill test that out later and i dont have movecraft-towny when i said towny i meant the offical plugin

**Comment by tskopen** [comment]
ok it works without it ima add it again to double check that it breaks without it

**Comment by tskopen** [comment]
ok i readded movecraft-combat and it still works so idk /: maybe it was a one time glitch its maybe me removeing it and readding it fixed it im not sure but its fixed now so illa close this issue if it comes up again ill reopen it and say what happened

**Comment by tskopen** [comment]
i cant find the close button /: normally its at the bottom of a thread buts it not

**Comment by tskopen** [comment]
wait nvm i found it when the craft is bumping into something it resets the cannon ill remove combat again test it and yeah

**Comment by tskopen** [comment]
nope still resets when it bumps into something even though i removed movecraft cannons heres log. https://mcpaste.io/702ee0b51b58a66b

**Comment by TylerS1066** [comment]
Thanks for all the help trying to debug this issue!

Please try this dev build and let me know how it does when bumping into things: https://github.com/TylerS1066/Movecraft-Cannons/suites/3263901626/artifacts/75960535

**Comment by tskopen** [comment]
im assuming i just update my movecraft-cannons with that? as in delete the old jar and replace it (ill do that)

**Comment by tskopen** [comment]
ayyy when the movecraft is blocked by a block the cannons dont reset now :D ty for the support also funny name for the dev build movecraft-cannons_asdojfhalskdjhflakjehatksljdfhal or smth hahaha

**Comment by TylerS1066** [comment]
Thanks for letting me know!  I'll work on cleaning things up and preparing an alpha release.
