### ISSUE TITLE
Aiming mode cannons bug

### ISSUE THREAD

**Issue by Mineshaft87** [TylerS1066/Movecraft-Cannons#14]
Movecraft: 8.0.0-a.4
Java: 16
paper 1.17.1-136
Movecraft-cannons: 1.a.3

I've noticed when activating the aiming mode (default: clock) in the most recent github version of cannons, that upon cruising forward leaving mode gets disabled. It seems movecraft doesn't keep up with cannons' aiming mode. This did NOT occur when manually flying, the aiming mode did not disable. Got this error in my console which might be a result of it. I can produce a video if need be.
![image](https://user-images.githubusercontent.com/84353484/134785562-33fdb80b-d0b1-4033-a72a-56387d2b6909.png)

**Comment by TylerS1066** [comment]
That error is intended for the first movement according to cccm5, it has nothing to do with this addon.

Do the cannons continue to function after movement?  If so, this is likely a problem with the cannons plugin itself not properly remembering the aiming mode when a cannon is moved.

**Comment by TylerS1066** [comment]
Were you able to test if the cannon is still a cannon after movement?

**Comment by Mineshaft87** [comment]
> Were you able to test if the cannon is still a cannon after movement?

I believe at some point the Cannons owner fixed the issue, not sure when but cannons do seem to work on the move now (just re-tried it)!
I'm using the most recent compiled version of cannons, heads up for anyone perhaps using the latest release on bukkit/spigot.

**Comment by TylerS1066** [comment]
Awesome!  I suspected this was a problem with the cannons plugin and not Movecraft-Cannons, hence my question to if they still fired or were registered.
