### ISSUE TITLE
Download?

### ISSUE THREAD

**Issue by GrandpaBlackTF2** [TylerS1066/Movecraft-Cannons#18]
I'm not sure how to download this. The artifact from the latest dev build has expired. Is there a .jar to download, or the src so I can compile it? I don't know how to compile it but by god I will learn.

**Comment by TylerS1066** [comment]
The main plugin page has a "Release" tab on the left, which is where we publish releases: https://github.com/APDevTeam/Movecraft-Cannons/releases

We also have continuous integration set up through GitHub Actions where you can download dev builds (not recommended).
