### ISSUE TITLE
Not functioning

### ISSUE THREAD

**Issue by GrandpaBlackTF2** [TylerS1066/Movecraft-Cannons#19]
Hey, this plugin no longer seems to work. Every time a ship moves, the cannons must be re-bought, stocked, and loaded. I am using eirikh's Movecraft fork (most recent version) and the normal cannons plugin, both work separately on my paper 1.18.2 server, but cannons are not being integrated to the crafts.

**Comment by goodroach** [comment]
If you're using eirikh's movecraft fork, then this plugin won't work for you. This plugin is for the base movecraft version only iirc, and I would ask eirikh about a cannons integration to his fork.

**Comment by GrandpaBlackTF2** [comment]
ah, I wasn't aware they were so different. Thank you :)

**Comment by GrandpaBlackTF2** [comment]
I follow the links on eirikh's Movecraft-Cannons page, and they always lead me back to AP's plugin. I am very new to all this, anyone have any idea how I could download eirikh's fork as a .jar?

thanks

**Comment by TylerS1066** [comment]
You'd have to ask Eirik, as far as I know he doesn't have any releases or working Cannons integration with his fork.
