### ISSUE TITLE
Fire cannons on left/right click

### ISSUE THREAD

**Issue by Nikkilectric** [TylerS1066/Movecraft-Cannons#21]
Would be really cool to have the ability to fire specific cannons when using left/right click and looking where you'd like to aim. Could be done using signs overtop of regular cannon signs or anything else.

A fork for the Cannons plugin for 1.20.4 can be found here:
https://github.com/Intybyte/Cannons

**Comment by TylerS1066** [comment]
That sounds like great additions to the base Cannons plugin.  Unfortunately, this addon is not used on the Airship Pirates server and we only maintain it in our free time and aren't interested in adding new features.
