### ISSUE TITLE
1.16.5 Support

### ISSUE THREAD

**Issue by Insilvon** [TylerS1066/Movecraft-Cannons#5]
Currently cannot be loaded with Eirikh's latest release, Paper 1.16.5, and Cannons 2.5.8.
Error below.

https://pastebin.com/bS6ihWjX

**Comment by TylerS1066** [comment]
Woops, this looks to be a dependency on Movecraft-Combat that shouldn't be there!  I'll get a fix for this to you ASAP.

**Comment by Insilvon** [comment]
Thanks so much!

**Comment by TylerS1066** [comment]
Try [this dev build](https://github.com/TylerS1066/Movecraft-Cannons/suites/2004309836/artifacts/40062614), it should fix this issue.

**Comment by Insilvon** [comment]
That fixed it, thank you!
