### ISSUE TITLE
Cannons have to be rebought when movecraft moves

### ISSUE THREAD

**Issue by JustinDevB** [TylerS1066/Movecraft-Cannons#6]
Whenever a movecraft is moved all bought cannons have to be rebought.

**Comment by TylerS1066** [comment]
What version of Minecraft, Movecraft, Cannons, Movecraft-Cannons and server software are you running?

In addition, what movements cause this (stick movements, cruise, rotate, etc)?

**Comment by JustinDevB** [comment]
Minecraft: 1.16.5
Movecraft: 7.0.0.1 for 1.8.8-1.16.2
Cannons: 2.5.10
Movecraft-Cannons: 1.a.0
Software: Purpur

Breaks on every type of ship movement.

**Comment by TylerS1066** [comment]
Movecraft-Cannons 1.a.0 only supports the alpha releases of Movecraft 8.0.

**Comment by JustinDevB** [comment]
Where do you find the alpha releases of 8.0?

**Comment by NicolasECP** [comment]
Currently this is the latest alpha: https://github.com/APDevTeam/Movecraft/releases/tag/8.0.0-a.2
