### ISSUE TITLE
Cannons and Server software incompatibilities?

### ISSUE THREAD

**Issue by TylerS1066** [TylerS1066/Movecraft-Cannons#7]
> Describe the bug
> The Cannons bug which involves them being re-created each time a movecraft vehicles moves and the player right clicks the corresponding Cannon design, seems to occur on paperspigot server versions #470+ #778 (latest) and the following plugins:
> 
> Movecraft 8.0.0-a.3
> Movecraft Cannons 1.a.0
> Movecraft Combat 2.a.0
> Movecraft Worldguard 1.a.0
> 1.16.5 version WG/WE/Protocol.
> Cannons v2.5.10 (latest)
> The following above plugin options alongside a 1.16.5 PURPUR server jar seem to work fine with cannons. Although a world i created and --forceUpgraded via a 1.16.5 paperspgiot server, copied onto my PURPUR test server recreates the same bug.
> 
> To Reproduce
> Create a server with the above listed plugins and try piloting a craft with a cannon on it, claim the cannon, move the craft, then right click the cannon again.
> 
> Expected behavior
> The bug should occur.
> 
> Screenshots
> https://imgur.com/a/1Wafc5J
> 
> short gif displaying the bug
> Versions (please complete the following information):
> 
> Mostly listed above
> Java 16
> Minecraft 1.16.5

**Comment by TylerS1066** [comment]
https://github.com/APDevTeam/Movecraft/issues/432

> I'd like to see if somebody else can reproduce this with a minimal plugin set (Movecraft, Cannons, ProtocolLib, Movecraft-Cannons) and if so, see if spigot, tuinity, and airplane have these issues. I'd like to narrow down which server software introduces the problem before looking into it too far.

**Comment by TylerS1066** [comment]
Actually, can you try this without Movecraft-WorldGuard installed?  It might be a similar bug to https://github.com/TylerS1066/Movecraft-Towny/issues/3 with both protection plugins interfering.

**Comment by jamesol1** [comment]
> Actually, can you try this without Movecraft-WorldGuard installed? It might be a similar bug to [TylerS1066/Movecraft-Towny#3](https://github.com/TylerS1066/Movecraft-Towny/issues/3) with both protection plugins interfering.

Tried it and the bug went away! My bad i thought i tested removing WG.

**Comment by Mineshaft87** [comment]
> Actually, can you try this without Movecraft-WorldGuard installed? It might be a similar bug to [TylerS1066/Movecraft-Towny#3](https://github.com/TylerS1066/Movecraft-Towny/issues/3) with both protection plugins interfering.

Removing WG solved the issue! My bad on that i thought i tested if WG was an issue. 
EDIT: reposted this comment with my new account.

**Comment by TylerS1066** [comment]
> Removing WG solved the issue! My bad on that i thought i tested if WG was an issue.
> EDIT: reposted this comment with my new account.

I've created a new issue on the Movecraft-WorldGuard GitHub to track this: https://github.com/APDevTeam/Movecraft-WorldGuard/issues/4
