### ISSUE TITLE
Cannons being unregistered on craft movement

### ISSUE THREAD

**Issue by TheHappyHopper** [TylerS1066/Movecraft-Cannons#8]
In the latest fork by eirikh the movecraft cannons plugin does not work, cannons get unregistered and need to be remade after any ship movement, tested on paper 1.16.5 778 with movecraft, and movecraft cannons

**Comment by TylerS1066** [comment]
This plugin does not support Eirik's fork, only releases from [APDevTeam](https://github.com/APDevTeam/Movecraft) are supported.

**Comment by TheHappyHopper** [comment]
oh shoot, the apdevteam version doesnt work at all yet, guess ill have to wait then
