### ISSUE TITLE
Cannon translation reports

### ISSUE THREAD

**Issue by TylerS1066** [TylerS1066/Movecraft-Cannons#9]
> Describe the bug
> Been having a bug where cannons get reset on the move and rotation. it happens on Tank craft(custom ground craft ) and submarine.
> 
> To Reproduce
> Steps to reproduce the behavior:
> No visible errors
> 
> Expected behavior
> I wanted the cannon to not get reset and work properly.
> 
> Screenshots
> None.
> 
> Versions (please complete the following information):
> 
> Movecraf: 8 `java CI Repair - signs #189`
> Java JDK 16.0.0
> Minecraft paper-1.16.5
> Additional context
> none

**Comment by TylerS1066** [comment]
https://github.com/APDevTeam/Movecraft/issues/436

**Comment by TylerS1066** [comment]
@acrticsludge I'd like to know if you are using any other addons.

**Comment by TylerS1066** [comment]
If you don't have either of the protection addons, then this may be the root cause of https://github.com/APDevTeam/Movecraft-WorldGuard/issues/4 and https://github.com/TylerS1066/Movecraft-Towny/issues/3 (and be related to #10).  If not, then look into those two issues.

**Comment by acrticsludge** [comment]
i have none of those addons

**Comment by TylerS1066** [comment]
Interesting, and to double check it resets cannons on movement some or all of the time?

**Comment by acrticsludge** [comment]
like the first cannon does not reset on movement but the second and rest do. its pretty interesting.

**Comment by TylerS1066** [comment]
@acrticsludge can you try this again with the latest Movecraft alpha (4) and Movecraft-Cannons alpha (1.a.1)?

**Comment by TylerS1066** [comment]
For anyone else having problems, please try the latest alpha.  If that doesn't work, try this dev built: https://github.com/TylerS1066/Movecraft-Cannons/actions/runs/1040628554.

If either of those things fixes your problem, please let me know.

**Comment by acrticsludge** [comment]
sure but ive enountered another possible movecraft bug and am working on resloving that first
edit: sorry for late responses ive been busy :p

**Comment by TylerS1066** [comment]
As discovered in #12 and mentioned in #10, this dev build may fix things: https://github.com/TylerS1066/Movecraft-Cannons/suites/3263901626/artifacts/75960535


If you are having problems, please try that dev build!  If nobody has a problem on the dev build, I'll be releasing it as an alpha soon.

**Comment by acrticsludge** [comment]
sure!

**Comment by TylerS1066** [comment]
Since there have been no reports of problems in 3 months, I am going to mark this as resolved!
